### ISSUE TITLE
Failure in meta_process: HSI-spatial calib prevents plotting spectra

### ISSUE THREAD

**Issue by CCampJr** [CCampJr/CRIkit2#85]
Loading in an image that has valid meta data in H5 header leads to (see below) when one attempts to get a point- or ROI-spectrum:

```
Something failed in meta_process: HSI-spatial calib
Was successful: True
HSI shape: (100, 100, 1600)
Converting HSI from int to float
Traceback (most recent call last):
  File "C:\Users\chc\Documents\PyDistros\WPy64-3740\python-3.7.4.amd64\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "c:\users\chc\documents\python\repos\crikit2\crikit\CRIkitUI.py", line 1485, in <lambda>
    lambda event: self._pointClick(event, self._pointSpectrumPlot))
  File "c:\users\chc\documents\python\repos\crikit2\crikit\CRIkitUI.py", line 1706, in _pointClick
    pass_fcn((x_loc, y_loc))
  File "c:\users\chc\documents\python\repos\crikit2\crikit\CRIkitUI.py", line 1727, in _pointSpectrumPlot
    x_pix = find_nearest(self.hsi.x, x_loc)[1]
  File "c:\users\chc\documents\python\repos\crikit2\crikit\utils\general.py", line 252, in find_nearest
    test = _np.abs(_np.array(np_vec)-to_find)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by CCampJr** [comment]
The problem occurs when the start, stop and step values in the meta data are stored as arrays (length 1) instead of floats or ints. This leads to a linspace creates an (N,1) array. The setter for hsi.x and hsi.y prevent setting as this is a 2D array.

Fixed by squeezing the linspace outputs (commit d3a8ad0bc8eccacff087a7e7927ca8a28d07171d)
